### PR TITLE
Add DC/OS packages for OpenWhisk

### PR DESCRIPTION
**Pull request by duynguyen**
Supporting packages to run OpenWhisk on DC/OS:
- apigateway
- consul
- registrator
- whisk-couchdb (pre-populated whisk data, currently using https://hub.docker.com/r/adobeapiplatform/whisk-couchdb/ built by @ddragosd )
- whisk-controller
- whisk-invoker

Thanks @ddragosd for your great help.

whisk-controller and whisk-invoker are using images on https://hub.docker.com/u/openwhisk/. Thanks @csantanapr for publishing!

### CODE REVIEW

**Comment by duynguyen** [comment]
Currently has a dependency on [openwhisk/openwhisk#2117](https://github.com/openwhisk/openwhisk/issues/2117).

**Comment by csantanapr** [comment]
@ddragosd I need help creating the image
How you created yours ?
I tried running docker commit to snapshot but that doesn't work since  the couchdb docker is configure to use a volume so I'm not committing anything that is mounted

**Comment by ddragosd** [comment]
@csantanapr 
I used the work on https://github.com/apache/incubator-openwhisk/pull/1928. The flow is like this:

1. spin up a couchDB docker image
2. execute the ansible scripts `initdb.yml` and `wipe.yml`
3. dump DBs from the couchDB container into  JSON files: `local_whisks` and `subjects` (back then it was not a separate DB for `activations`)
4. create a simple `whisk-couchdb` container that uses these exported files to configure the DB at startup. See: [Dockerfile](https://github.com/ddragosd/openwhisk/blob/1d45e9dba42450ee4a05f74c4da6cdd465cf9919/tools/db/docker/Dockerfile) ,  [init.sh](https://github.com/ddragosd/openwhisk/blob/1d45e9dba42450ee4a05f74c4da6cdd465cf9919/tools/db/docker/init.sh), and [import.sh](https://github.com/ddragosd/openwhisk/blob/1d45e9dba42450ee4a05f74c4da6cdd465cf9919/tools/db/docker/import.sh) ,  then copy the exported JSON files into this container.
5. when this container stars, if there's no DB, it will initialize them from these exposed JSON files. If  DBs are present, it won't modify them.

I'm happy to help; we just need to make up our minds and see where we want to place such a script. Initially I placed it into the main repo; we then had conversations about continuously testing everything that goes into the main repo; this was a challenge b/c generating this container is dependent on infrastructure code which is not so easy to _unit-test_ . Generating this image following the same flow would imply to clone the main repo, b/c we need the `ansible` folder, then execute the script somehow. Another problem we need to fix then is that ansible makes some assumptions about where each file is, and we'd have to find a way to clone the repo, then copy the script inside the cloned repo, etc. 

At this moment I'm OK with any option, as long as we make progress. Pinging @markusthoemmes and @rabbah too.

**Comment by rabbah** [comment]
I think we were converging here: https://github.com/apache/incubator-openwhisk/pull/1928#issuecomment-296378975

**Comment by ddragosd** [comment]
👍  @rabbah . @csantanapr did you get the chance to test @rabbah's suggestion or that's what we need to do next ?

**Comment by ddragosd** [comment]
@duynguyen let's move this PR into the new repo for Mesos: https://github.com/apache/incubator-openwhisk-deploy-mesos .

In that new repo we can place DC/OS Universe releases so that Mesos admins can install the required packages very easy.

**Comment by duynguyen** [comment]
Closing this PR here. DC/OS packages will be in https://github.com/apache/incubator-openwhisk-deploy-mesos (PR will follow soon).

**Pull request closed without merging**
