### PR TITLE
Refactored to be more comprehensive.

### PR DESCRIPTION
**Pull request by jordanyaker**
Updated the docker-compose project to be more comprehensive with the following:

- Switched to the openwhisk/apigateway image.
- Created a full deployment with the `make deploy` command.
- Added a unique docker environment for Ansible.
- Added the configuration of CouchDB to set the `reduce_limit` param.
- Added a post-deployment step to create the `whisk.properties` file and install the OpenWhisk Catalog.
- Updated the quick-start to use new/shared commands.
- Added the installation of route management for the API Gateway.
- Updated the configuration of the API Gateway in Docker compose to work with route management.

### CODE REVIEW

**Comment by jordanyaker** [comment]
I'm not sure why Travis keeps failing.  I'm able to run this locally without any issues:

    initializing CLI ...
    REQUEST:
    [GET]	https://localhost:443/api/v1/namespaces
    Req Headers
    {
      "Authorization": [
        "Basic MjNiYzQ2YjEtNzFmNi00ZWQ1LThjNTQtODE2YWE0ZjhjNTAyOjEyM3pPM3haQ0xyTU42djJCS0sxZFhZRnBYbFBrY2NPRnFtMTJDZEFzTWdSVTRWck5aOWx5R1ZDR3VNREdJd1A="
      ]
    }
    RESPONSE:Got response with code 200
    Resp Headers
    {
      "Access-Control-Allow-Headers": [
        "Authorization, Content-Type"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ],
      "Connection": [
        "keep-alive"
      ],
      "Content-Length": [
        "9"
      ],
      "Content-Type": [
        "application/json; charset=UTF-8"
      ],
      "Date": [
        "Wed, 22 Mar 2017 19:57:29 GMT"
      ],
      "Server": [
        "openresty/1.9.7.3"
      ]
    }
    Response body size is 9 bytes
    Response body received:
    ["guest"]
    ok: whisk auth set to 23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP
    ok: whisk API host set to localhost:443
    ok: whisk namespace set to guest

**Comment by csantanapr** [comment]
@ddragosd could you review this PR?

**Comment by jordanyaker** [comment]
I have spotted one problem that I'm not quite sure how to resolve.  [openwhisk/openwhisk-apigateway](https://github.com/openwhisk/openwhisk-apigateway) has a conf file with a hard-coded IP address configuration for the upstream address in the [managed_endpoints.conf](https://github.com/openwhisk/openwhisk-apigateway/blob/master/conf.d/managed_endpoints.conf) file as follows:

    set $upstream https://172.17.0.1;

I've been trying to figure out a way to make this happen and have had 0% success so far.  The only thing I could think of was to submit a PR to that project to allow for an env variable to set the gateway address/subnet.

I'm interested in any thoughts anyone might have.

**Comment by jordanyaker** [comment]
So, I talked with @codymwalker on Slack.  It looks like the only thing that was missing was the declaration of the host IP.  Once I did `DOCKER_HOST_IP=172.18.0.1 make launch` everything was copacetic.

**Comment by ddragosd** [comment]
@csantanapr ACK 

@jordanyaker can we extract the `DOCKER_HOST_IP` automatically ?

**Comment by jordanyaker** [comment]
I've been trying to think about that myself.  The problem with that, is that depending on the OS, we have no idea what the right value would be.  In Ubuntu, I was able to directly use the bridge IP of `172.18.0.1` as noted above.  However, in Mac OS, because of the way that docker runs, I had to use the machine's IP on the network.

**Comment by csantanapr** [comment]
@codymwalker can you provide any help on how to get out of this catch 22?

Call me ignorant 😃 , Any changes we can do on apigateway config?, why does the gateway needs a specific ip of the docker host?

**Comment by ddragosd** [comment]
@jordanyaker the ansible scripts are needed here just to configure the DB b/c the ones found in the OpenWhisk repo were not reusable ?

**Comment by jordanyaker** [comment]
@ddragosd the Ansible scripts were already in play in the current `master` branch.  I added the `configdb.yml` task because I found that once I added enough stuff to the CouchDB it was freaking out.  As a result, I added the task to set the `reduce_limit` configuration.

**Comment by ddragosd** [comment]
I’m wondering whether it’s easier to maintain the logic setting `reduce_limit` in [initdb.yml](https://github.com/openwhisk/openwhisk/blob/master/ansible/tasks/initdb.yml); pinging @markusthoemmes as well.

I’m also trying to see if we can keep the ansible scripts in one place (into the main openwhisk repo, where the rest of the playbooks are). We'll soon be building a standalone docker image for the DB to be reused in Mesos and Kubernetes deployments and we'll be reusing the playbooks in there. See https://github.com/openwhisk/openwhisk/pull/1928

**Comment by ddragosd** [comment]
@jordanyaker thanks to @csantanapr we have a `couchdb` image available in Docker Hub: https://hub.docker.com/r/openwhisk/couchdb-snapshot/ .

**Comment by rabbah** [comment]
This generally looks good. Needs a rebase though but Travis is broken.

**Comment by jordanyaker** [comment]
It's been a while since I've used this project.  Is there still a need for this PR? @ddragosd

**Comment by Shillaker** [comment]
I hate to be a +1 spammer but I'd really like to see this merged in (if you have the time), the changes are super useful

**Comment by rabbah** [comment]
need to resolve a couple of conflicts - @jordanyaker if you can't get to it I can give it a shot or @Shillaker if you're up for it.

**Comment by Shillaker** [comment]
I'm picking my way through it now, think I'm almost there. Should have something in an hour or so.

**Comment by ddragosd** [comment]
I'm closing this one, as the work is now happening in #72

**Pull request closed without merging**
