### PR TITLE
Add support for installing optional packages.

### PR DESCRIPTION
**Pull request by jthomas**
Downloads package repos, installs shared actions and starts provider containers for alarms, kafka and cloudant packages.

```
$ make create-provider-alarms
```

Uses additional Docker compose file for managing container configuration for package provider images.

### CODE REVIEW

**Comment by jthomas** [comment]
Good point - let me add the docs for this!

**Comment by jthomas** [comment]
@ddragosd done.

**Comment by jthomas** [comment]
Looks like Travis was having network issues - do we need to re-run the build?

**Comment by ddragosd** [comment]
The build was fixed by @tysonnorris . We can merge this like this, but I'm testing locally and having some issues after executing `make create-provider-alarms`: 

```
ok: updated action alarmsWeb/alarmWebAction
Starting openwhisk_redis_1 ... done
Starting openwhisk_db_1 ... done
Starting openwhisk_zookeeper_1 ... done
Starting openwhisk_kafka_1 ... done
Starting openwhisk_controller_1 ... done
Starting openwhisk_apigateway_1 ... done
Starting openwhisk_alarmsprovider_1 ... error

ERROR: for openwhisk_alarmsprovider_1  Cannot start service alarmsprovider: driver failed programming external connectivity on endpoint openwhisk_alarmsprovider_1 (84af8ca96fcb7355b7f62b04a90429c3fa13c0042d44c8bf7ed46a3addce3402): Error starting userland proxy: Bind for 0.0.0.0:8081 failed: port is already allocated

ERROR: for alarmsprovider  Cannot start service alarmsprovider: driver failed programming external connectivity on endpoint openwhisk_alarmsprovider_1 (84af8ca96fcb7355b7f62b04a90429c3fa13c0042d44c8bf7ed46a3addce3402): Error starting userland proxy: Bind for 0.0.0.0:8081 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
```

**Comment by jthomas** [comment]
@ddragosd Do you already have something running on port 8081? The compose files binds 8080 from the alarmsprovider container to 8081. 

Maybe an old instance of the container?

**Comment by ddragosd** [comment]
I had originally thought it's `docker`, but on my MAC I'm seeing another process indeed: 
```
sudo lsof -i TCP:8081 | grep LISTEN
macmnsvc  62  mfe   24u  IPv6 0x200e0465dd32d1e5      0t0  TCP *:sunproxyadmin (LISTEN)
```
https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=8081

How about we check if the ports are in use before starting to install a package ?

**Comment by jthomas** [comment]
@ddragosd good idea - done.

**Comment by ddragosd** [comment]
@jthomas 💯

**Pull request merged**
