### PR TITLE
Add wait-for-docker-compose-up

### PR DESCRIPTION
**Pull request by Juice10**
Locally I was having issues where `make quick-start` would start interacting with containers before they where up and running. This triggered me to build `make wait-for-docker-compose-up`.

`wait-for-compose-up` waits until all docker containers are up and running before continuing. It times out after 30 seconds and outputs the status of all the containers that are and aren't running at that point in time to allow you to understand what is going wrong.

`wait-for-compose-up` is also added as part of `quick-start`.

`wait-for-compose-up` also includes a special mode when running `VERBOSE=true` where it will give you a live update on what the container status is. See screen capture of that mode below:

wait-for-docker-compose-up

### CODE REVIEW

**Comment by alvarolopez** [comment]
I am having the same issue (the controller needs to be restarted manually, otherwise the `quick-start` hangs out forever...

**Comment by rabbah** [comment]
this is failing in travis - i rebased it to master though.

**Comment by rabbah** [comment]
@Juice10 any chance you can debug what's happening that's blocking us from merging this?

**Comment by Juice10** [comment]
@rabbah looking at it right now

**Pull request merged**
