### PR TITLE
ActionLoop starter kit

### PR DESCRIPTION
**Pull request by sciabarracom**
Attached there is a bare-bones (but fully functional) runtime for people to be used as a starting point to develop new runtimes with ActionLoop. Once it is merged I will write the documentation.

### CODE REVIEW

**Comment by sciabarracom** [comment]
I close this as I resubmitted a version rebased

**Comment by csantanapr** [comment]
Why? You can rebase and force push, no need for a new PR

**Comment by sciabarracom** [comment]
Huh! I did not think about it

**Comment by csantanapr** [comment]
Yeah I do it all the time as long I’m the only contributor in the PR. Even squash 
Usually I do a lot of commits when is in draft/wip 

When I think is ready for review and merge I rebase squash into one commit and force push.

**Pull request closed without merging**
