### PR TITLE
WIP: attempt to resolve path errors on Travis build.

### PR DESCRIPTION
**Pull request by mrutkows**

### CODE REVIEW

**Comment by ddragosd** [comment]
I think something changed in Travis ? I'm experiencing the same issue on #43.

**Comment by mrutkows** [comment]
@ddragosd it seems to be an actual error in the setup script trying to download the docker compose binary into (piped) into the name of the 'docker-compose' directory which should have never succeeded.

**Comment by ddragosd** [comment]
I see what you're saying. It looks like [Travis made a change recently](https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch), which might cause us to update the scripts.

**Comment by ddragosd** [comment]
@mrutkows this did it: https://github.com/ddragosd/incubator-openwhisk-devtools/blob/bdd909031ab6bd5ba83213f6df59f63c1ee1c76d/docker-compose/.travis/setup.sh  
I took some inspiration from one of your previous commits.

In the new trusty update on Travis, `docker-compose` `1.13.0` is already installed. The current script installs `1.8.1`, but we should reuse `1.13.0`. 

The reason why the previous scripts was working fine has to do with the working directory. I have reasons to believe in the new Travis version this has changed as well; otherwise the old script couldn't have completed successfully.

**Comment by mrutkows** [comment]
@ddragosd wanted to fix this myself after spending dinner with my wife )

**Comment by ddragosd** [comment]
@mrutkows feel free to cherry-pick or update your current scripts. We can probably merge your PRs first. You might wanna pull 1 more change in, in order to fix the docker-compose build with OW: https://github.com/apache/incubator-openwhisk-devtools/pull/43/commits/871ea5d86b2b13837974aeb254db4900cef1c203

**Comment by mrutkows** [comment]
I merged the referenced PR (i.e., 871ea5d) and will build another commit off of that to add a bit more checking and clarity into the setup.sh script.

**Pull request closed without merging**
