### PR TITLE
[docker-compose] - remove consul and registrator services

### PR DESCRIPTION
**Pull request by duynguyen**
according to recent changes in OW main repo.

### CODE REVIEW

**Comment by ddragosd** [comment]
thanks a lot @duynguyen . I'm reviewing this now.

**Comment by ddragosd** [comment]
👍 LGTM. I've also tested it and it works great. Thanks !

**Comment by duynguyen** [comment]
thanks @ddragosd :)

**Comment by alexkli** [comment]
The [readme](https://github.com/apache/incubator-openwhisk-devtools/blame/192197e4d912d6e6c9d51f6fd0b7762439538576/docker-compose/README.md#L20) and the [Makefile port check](https://github.com/apache/incubator-openwhisk-devtools/blob/192197e4d912d6e6c9d51f6fd0b7762439538576/docker-compose/Makefile#L58) in docker-compose still include the Consul ports. I guess they can be removed from there as well?

**Comment by duynguyen** [comment]
oops forgot it. @alexkli do you want to create the patch?

**Comment by alexkli** [comment]
@duynguyen there you go: #55

**Comment by duynguyen** [comment]
thanks @alexkli !

**Pull request merged**
