### PR TITLE
Adapt the DB config to match with pureconfig switch

### PR DESCRIPTION
**Pull request by chetanmeh**
For changes done via apache/incubator-openwhisk#3369

### CODE REVIEW

**Comment by jthomas** [comment]
Looks like the build has got stuck on this: https://travis-ci.org/apache/incubator-openwhisk-devtools/builds/352461291

Can someone restart it?

**Comment by csantanapr** [comment]
I restarted here: https://travis-ci.org/apache/incubator-openwhisk-devtools/builds/352461291
@jthomas you have write access to the repo you can restart any travis build.

**Comment by csantanapr** [comment]
I think is a problem with controller now being https by default instead of http

https://github.com/apache/incubator-openwhisk/commit/a8476ab970b4f8804d0d26fa319fe4aaa7c9ab04

cc @vvraskin

**Comment by csantanapr** [comment]
hum, it might not be related to https
```
until $(curl --output /dev/null --silent --head --fail http://10.20.0.239:8888/ping); do printf '.'; sleep 5; done
..........................................................................................................................................................................................................................................
```
Since the default in purefonfig is `http`
CONFIG_whisk_controller_protocol
https://github.com/apache/incubator-openwhisk/commit/a8476ab970b4f8804d0d26fa319fe4aaa7c9ab04#diff-de8780464afb147e69223943ad23af93R11

**Comment by chetanmeh** [comment]
The build is getting stuck in controller startup which fails with following error

```
Exception in thread "main" akka.ConfigurationException: ActorSystem [akka://controller-actor-system] needs to have a 'ClusterActorRefProvider' enabled in the configuration, currently uses [akka.actor.LocalActorRefProvider]
	at akka.cluster.Cluster.<init>(Cluster.scala:71)
	at akka.cluster.Cluster$.createExtension(Cluster.scala:34)
	at akka.cluster.Cluster$.createExtension(Cluster.scala:29)
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:880)
	at akka.actor.ExtensionId$class.apply(Extension.scala:78)
	at akka.cluster.Cluster$.apply(Cluster.scala:29)
	at whisk.core.loadBalancer.ShardingContainerPoolBalancer.<init>(ShardingContainerPoolBalancer.scala:60)
	at whisk.core.loadBalancer.ShardingContainerPoolBalancer$.loadBalancer(ShardingContainerPoolBalancer.scala:295)
	at whisk.core.controller.Controller.<init>(Controller.scala:121)
	at whisk.core.controller.Controller$.main(Controller.scala:232)
	at whisk.core.controller.Controller.main(Controller.scala)
```

This is possibly due to [switch of default](apache/incubator-openwhisk#3400) `LoadBalancerProvider` to `ShardingContainerPoolBalancer` which instantiates the cluster. Currently the docker compose setup has `CONFIG_akka_actor_provider=local` set. Not sure if just setting it to cluster would make it work

**Comment by csantanapr** [comment]
Yes go ahead and do the work to collect anything you need into a tgz then later I can hook it up with an upload  with @rabbah

**Comment by chetanmeh** [comment]
The build now passed with switch to cluster mode. Locally also it works fine

**Pull request merged**
