### PR TITLE
Add teraform plugin for wskdeploy tool.

### PR DESCRIPTION
**Pull request by lzbj**

### CODE REVIEW

**Comment by lzbj** [comment]
@mrutkows , please help review, thanks a lot.

**Comment by ddragosd** [comment]
@lzbj any chance we can add some tests for this code and a travis script ?

**Comment by lzbj** [comment]
@ddragosd , thanks for your comments, I'll try to add some scripts to make some minimum gate for this patch.

**Comment by mrutkows** [comment]
@ddragosd I was hoping we would treat this as an experimental subproject under "devtools" (as this repo. seems to be where we start working out new deployment tools) and add Travis/tests over time.  I would very much like to get this code accepted and open issues to track for future work to provide integration tests and include in CI.  At this point, I do not know when we can resource these features, but would hate not to have the work "in the community" so perhaps we can attract new people with interest in TerraForm with OpenWhisk.

**Comment by ddragosd** [comment]
> treat this as an experimental subproject under "devtools" 

👍 . Let's mark it as experimental then, either in the README or in the folder name.

**Comment by lzbj** [comment]
@mrutkows @ddragosd , update the readme, please review, thanks.

**Comment by ddragosd** [comment]
thanks @lzbj

**Comment by mrutkows** [comment]
@ddragosd thanks Dragos

**Pull request merged**
